global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true
  slack_api_url: 'https://hooks.slack.com/services/REPLACE/WITH/ACTUAL'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'team-emails'
  routes:
  - match:
      severity: critical
    receiver: 'pager-duty'
    continue: true
  - match:
      severity: warning
    receiver: 'slack-notifications'
    continue: true
  - match_re:
      service: mongodb|microservice-api
    receiver: 'db-team'
    group_wait: 1m

receivers:
- name: 'team-emails'
  email_configs:
  - to: 'team@example.com'
    send_resolved: true
    html: '{{ template "email.default.html" . }}'
    headers:
      subject: '{{ template "email.default.subject" . }}'

- name: 'pager-duty'
  pagerduty_configs:
  - service_key: REPLACE_WITH_SERVICE_KEY
    send_resolved: true

- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    title: '{{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}'
    title_link: 'https://grafana.yourdomain.com/d/microservice-dashboard'
    footer: 'Microservice Monitoring'
    actions:
    - type: button
      text: 'View Dashboard'
      url: 'https://grafana.yourdomain.com/d/microservice-dashboard'

- name: 'db-team'
  email_configs:
  - to: 'db-team@example.com'
    send_resolved: true
    html: '{{ template "email.default.html" . }}'
    headers:
      subject: '{{ template "email.default.subject" . }}'
  slack_configs:
  - channel: '#db-alerts'
    send_resolved: true
    title: '{{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}'

templates:
- '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service'] 